version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8080"
    environment:
      - PORT=${PORT}
      - ORIGIN=${ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - DB_PORT=${DB_PORT}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_CLUSTER=${DB_CLUSTER}
      - DB_CLUSTER_NAME=${DB_CLUSTER_NAME}
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-api.rule=Host(storyquests-storyquests-zqf2at-02ff9a-95-164-55-96.traefik.me)"
      - "traefik.http.routers.backend-api.entrypoints=websecure"
      - "traefik.http.routers.backend-api.tls.certResolver=letsencrypt"
      - "traefik.http.services.backend-api.loadbalancer.server.port=8080"
      - "traefik.http.routers.backend-api.middlewares=backend-headers"
      - "traefik.http.middlewares.backend-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"

networks:
  dokploy-network:
    external: true
